### ISSUE TITLE
Adding [jpshare] to Sidebar using Text Widget?

### ISSUE THREAD

**Issue by vilav** [jeherve/jp-sd-shortcode#2]
Hi

Thanks for the plugin. Trying to add this to the sidebar. You've mentioned that it'll work anywhere within the loop but I reckon the sidebar isn't part of the loop (sorry just beginning WP). 

Is there  a way I could get this to work on the sidebar for all posts?

Thanks

**Comment by jeherve** [comment]
You'd need to create a loop in your sidebar. You can read more about it here:
https://codex.wordpress.org/The_Loop
