### ISSUE TITLE
Stopped showing in custom post type

### ISSUE THREAD

**Issue by joao2507** [jeherve/jp-sd-shortcode#3]
Hi guy!

The sharing buttons have recently stopped appearing on custom types pages.
something changed?

Example: http://www.diariodosertao.com.br/coluna/corrupcao-ditadura-e-processo-legal

**Comment by jeherve** [comment]
Could you go to Settings > Sharing in your dashboard, and make sure sharing is enabled for your post type?

**Comment by joao2507** [comment]
Hmm...

I was looking for this screen ... the strangest thing is that it was already setting up and working, but recently I was reported on the problem.

Thank you very much for your attention and congratulations for the work.
