### ISSUE TITLE
Not working as expected.

### ISSUE THREAD

**Issue by TwisterMc** [jeherve/jp-sd-shortcode#5]
This plugin doesn't work as I'd expect. It only works if share buttons are already on the page. If they aren't, then the shortcode doesn't do anything. The reason I wanted a shortcode was to allow me to put the share buttons wherever I wanted.

Is there a way to output the share buttons where the short-code is and nowhere else?

**Comment by jeherve** [comment]
> It only works if share buttons are already on the page. 

Yes, if you have disabled the sharing buttons on a page thanks to the built-in options, those options will also disable any buttons added by the shortcode. It was built to work that way.

If you want to display sharing buttons regardless of sharing settings, you will not be able to use my plugin. You will need to build your own custom solution, based on this post for example:
https://jetpack.com/2013/06/10/moving-sharing-icons/
